SELECT 
    I.STORE_ID,
    ST.STORE_NAME,
    COUNT(DISTINCT I.PRODUCT_ID) AS QTD_PRODUTOS,
    SUM(I.PRODUCT_INVENTORY) AS ESTOQUE_TOTAL
FROM CO.INVENTORY I
LEFT JOIN CO.STORES ST
    ON I.STORE_ID = ST.STORE_ID
GROUP BY 
    I.STORE_ID,
    ST.STORE_NAME;
