SELECT
    C.CUSTOMER_ID AS ID_CLIENTE,
    C.FULL_NAME AS NOME_CLIENTE,
    O.ORDER_STATUS AS STATUS_PEDIDO,
    O.ORDER_ID ID_PEDIDO,
    SUM(OI.UNIT_PRICE * OI.QUANTITY) AS TOTAL_PEDIDO,
    P.PRODUCT_NAME NOME_PRODUTO
FROM CO.CUSTOMERS C
LEFT JOIN CO.ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
LEFT JOIN CO.ORDER_ITEMS OI
    ON O.ORDER_ID = OI.ORDER_ID
LEFT JOIN CO.PRODUCTS P
    ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY 
    C.CUSTOMER_ID,
    C.FULL_NAME,
    O.ORDER_STATUS,
    O.ORDER_ID,
    P.PRODUCT_NAME;
